Add `results --fail-on-error/-F` flag
openSUSE/osc pull request #1573
Opened 2024-06-05 09:27 UTC by saschagrunert

This allows to exit with `1` in case any build fails to provide feedback to end-user scripts.

Refers to: https://github.com/kubernetes/release/issues/3632

2024-06-05 09:28 UTC, pep8speaks commented
Hello @saschagrunert! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`osc/core.py`](https://github.com/openSUSE/osc/blob/675f2b32d0995a5015a28b4e390c486536f860ca/osc/core.py):

> [Line 4092:121](https://github.com/openSUSE/osc/blob/675f2b32d0995a5015a28b4e390c486536f860ca/osc/core.py#L4092): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 4147:66](https://github.com/openSUSE/osc/blob/675f2b32d0995a5015a28b4e390c486536f860ca/osc/core.py#L4147): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'

2024-06-07 09:35 UTC, dmach requested changes
It's a good idea, but the `sys.exit()` call needs to be replaced with something else.

2024-06-10 07:40 UTC, saschagrunert commented on osc/core.py
> +        sys.exit(1)
Yeah I see. OTOH methods like `unpack_srcrpm`, `link_pac` and `aggregate_pac` also `sys.exit` directly. So I thought that would be a possible way to do.

2024-06-11 06:21 UTC, dmach commented on osc/core.py
> +        sys.exit(1)
> Yeah I see. OTOH methods like `unpack_srcrpm`, `link_pac` and `aggregate_pac` also `sys.exit` directly. So I thought that would be a possible way to do.

The old code has issues. Let's do it better than our predecessors.
How about the following?

```
def get_results(
    apiurl: str,
    project: str,
    package: str,
    verbose=False,
    printJoin="",
    out: Optional[dict] = None,
    *args,
    **kwargs
):
    ...
    # for simplicity so we don't have to always test `out` for None
    if out is None:
        out = {}
    ...
    out["failed"] = ...
```

and then we would call it this way:
```
out = {}
result = get_results(..., out=out)
```

2024-06-11 08:18 UTC, saschagrunert commented on osc/core.py
> +        sys.exit(1)
Sounds good, changed as suggested :+1:

2024-06-20 07:58 UTC, dmach commented
I've rebased the PR, resolved conflicts and force-pushed back to your branch.
The PR looks good to me and if the tests pass, I'll merge it.

2024-06-20 08:00 UTC, saschagrunert commented
Thank you @dmach! :pray:

2024-06-20 09:06 UTC, merged